# Generated by Django 5.2.17 on 2026-09-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special status', 'can red all books')]},
        ),
    ]
